### ISSUE TITLE
START command makes result open in a new window

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#100]
Scripts `run.bat` and `test.bat` use the START command. This makes them open `star.exe` and `nunit3-console.exe` in a new window.

Is that needed?

This is especially troublesome in `nunit3-console.exe`, because I cannot see the test result. The result is displayed in the window that is immediately closed afterwards.

**Comment by KmaTTi89** [comment]
@warpech 
I can fix that.
You can see the result after tests run in TestResult.xml file too.

**Comment by warpech** [comment]
Thanks, please fix that.

**Comment by KmaTTi89** [comment]
@warpech 
Done in https://github.com/StarcounterSamples/KitchenSink/pull/101
