### ISSUE TITLE
Update the usage of puppet-redirect

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#12]
Switch to be using the new path `/sys/puppet-redirect/puppet-redirect.html`.

Please release a new version when done.

**Comment by tomalec** [comment]
and what about https://github.com/PuppetJs/puppet-redirect/issues/1#issuecomment-170517367?

**Comment by warpech** [comment]
I will reply in https://github.com/PuppetJs/puppet-redirect/issues/1#issuecomment-170517367, but I don't think that issue blocks this in any way. The path to the file will stay the same.

**Comment by tomalec** [comment]
But the doubt on "read-only" remains, so should it be used with two- or
one-way Polymer binding.
12 sty 2016 14:59 "Marcin Warpechowski" <notifications@github.com>
napisał(a):

**Comment by warpech** [comment]
Closing this, as there is already a richer discussion in duplicate issue #21
