### ISSUE TITLE
Basic HTML/CSS pattern in KitchenSink (apply Bootstrap)

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#15]
Use the same HTML/CSS pattern in KitchenSink as in sample apps. Now it is completely misleading

Needs to take the referenced issues into the account

**Comment by warpech** [comment]
Basically, this means to adopt the suggested Bootstrap pattern in KitchenSink. This is a suggestion to be followed in all of the apps.

**Comment by warpech** [comment]
This is a basis for advertising a common pattern that will be recognized by in https://github.com/Starcounter/RebelsLounge/issues/14

**Comment by warpech** [comment]
@aloscha will add the correct Bootstrap pattern to the KitchenSink

I will write an article about it.

**Comment by warpech** [comment]
To wrap up - the task is to apply the Bootstrap pattern used in the Products app (https://github.com/StarcounterSamples/People/blob/master/src/People/wwwroot/People/viewmodels/OrganizationPage.html) to KitchenSink.

**Comment by warpech** [comment]
The following *divitis* (existence of wrapping divs) is totally not needed:

```html
<template>
    <template is="dom-bind">
        <div>
            <p class="lead">JSON's primitive value type <code>string</code> can be mapped directly to HTML form <code>input type="text"</code>.</p>
        </div>
        <div>
            <h5>Listening to changes</h5>
        </div>
        <div>
            <p>Bind to <code>::change</code> listener to send the new value to the server when the field is unfocused. Read more about the target change events in the <a href="https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#two-way-native">Polymer docs</a>.</p>
        </div>
        <div>
            <label class="control-label">{{model.NameReaction}}</label>
        </div>
```

Should be changed to this:

```html
<template>
    <template is="dom-bind">
        <p class="lead">JSON's primitive value type <code>string</code> can be mapped directly to HTML form <code>input type="text"</code>.</p>

        <h5>Listening to changes</h5>

        <p>Bind to <code>::change</code> listener to send the new value to the server when the field is unfocused. Read more about the target change events in the <a href="https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#two-way-native">Polymer docs</a>.</p>

        <label class="control-label">{{model.NameReaction}}</label>
```

It is an artifact from old requirements of layout editor that also exists in other sample apps. But this should not be repeated in Kitchen Sink. It should also be removed from other sample apps in future.

@aloscha can you please fix? After this we can merge.

This was also found by @miyconst in his comment: https://github.com/StarcounterSamples/KitchenSink/commit/57ec118333e4b46b745b6b26afca04dab17613f1

**Comment by warpech** [comment]
Looks very good now! Some comments before merging:

1. Please just remove the duplicate `<h1>` in `BreadcrumbPage.html`
2. Please apply Bootstrap classes to `<button>` throughout the project. Right now only `<button>` in `FileUploadPage.html` has Bootstrap classes.

After this please merge to `master`, unless @miyconst provides some comments.

**Comment by aloscha** [comment]
Fixed @warpech

**Comment by warpech** [comment]
Great! Selenium tests are passing, so please merge to `master`
