### ISSUE TITLE
"Map" link doesn't work

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#16]

**Comment by aloscha** [comment]
The error receives:
`puppet.js:307 GET http://localhost:8080/KitchenSink/Geo 404 (Not Found)PuppetNetworkChannel.xhr @ puppet.js:307PuppetNetworkChannel.changeState @ puppet.js:246PuppetDOM.morphUrl @ puppet-dom.js:67PuppetDOM.clickHandler @ puppet-dom.js:100
puppet.js:285 Uncaught Error: PuppetJs JSON response error. Server responded with error 404 Not Found

Error 404: Resource "/kitchensink/geo" not found.`

**Comment by aloscha** [comment]
After fixed on NavPage, the error is the same as in https://github.com/StarcounterSamples/KitchenSink/issues/10

**Comment by warpech** [comment]
This is fixed by @aloscha in #10
