### ISSUE TITLE
Add Selenium tests

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#18]
This issue is to explore adding Selenium tests to KitchenSink.

All of the demonstrated material from KitchenSink should also be tested in KitchenSink.Test.

KitchenSink tests should be part of Starcounter build process, to catch breaking changes.

**Comment by warpech** [comment]
In result, write an article about Selenium testing for starcounter.io

**Comment by warpech** [comment]
I have pushed an initial version of tests. They are added to the solution as a separate project.

The tests pass for me in Firefox and Chrome (Windows 10 64 bit).

@miyconst Could you please check if it works for you too?

![image](https://cloud.githubusercontent.com/assets/566463/13609425/37ed33d6-e559-11e5-945a-0932eb0cc2a6.png)

**Comment by warpech** [comment]
IE11 has some problems which have been submitted to https://github.com/webcomponents/webcomponentsjs/issues/504 and https://github.com/SeleniumHQ/selenium/issues/1765. Hopefully someone helps.

**Comment by miyconst** [comment]
I confirm that tests pass for me in Chrome and FF.

**Comment by miyconst** [comment]
Also confirm that two of the tests fail in IE. Edge didn't even start for me.

**Comment by warpech** [comment]
Thanks for checking! Edge driver is not even there, so it won't start. I will add it when I find it on NuGet.

**Comment by warpech** [comment]
It seems that using NuGet for installing drivers was a bad idea because 3rdparty drivers are unmaintained there.

I switched to use RemoteWebDriver NuGet package (which also works fine on a local machine). It complicated the installation procedure, but allows us to use the most recent drivers, including Edge.

Installation instructions are here: https://github.com/warpech/SeleniumTest

@miyconst, @tomalec could you please check if the tests now work for you as well in Firefox, Chrome and Edge? Please report problems with the installation instructions if you find any.

IE still doesn't work, but that's beyond me to fix.

**Comment by miyconst** [comment]
I have finally set up the environment (a Hyper-V virtual machine) for selenium testing. It took me almost two hours.

And I confirm that all tests pass.

**Comment by miyconst** [comment]
@warpech it would be good to add java download link: https://java.com/en/download/, and I tested with `selenium-server-standalone-2.53.0.jar`.

**Comment by warpech** [comment]
> I have finally set up the environment (a Hyper-V virtual machine) for selenium testing. It took me almost two hours.

Yikes. In your setup, did you run Starcouner and `KitchenSink.exe` in that Virtual Machine, or in the host machine?

**Comment by miyconst** [comment]
Everything is inside the virtual machine.

You don't have much room to speed it up. Keep in mind, that everything were installed from scratch, Windows, Visual Studio, NodeJs, Bower, GitHub, Java.

**Comment by warpech** [comment]
> You don't have much room to speed it up. Keep in mind, that everything were installed from scratch, Windows, Visual Studio, NodeJs, Bower, GitHub, Java.

There is room. You can start Starcounter and the tested app on the host and connect to the remote (virtual machine) that runs the Selenium driver server. Just change the IP of the Selenium server from 127.0.0.1 to that of the Selenium server.

I have created a separate issue to track how to configure this in our CI: https://github.com/Starcounter/CompanyTrack/issues/185

**Comment by warpech** [comment]
I have written an article about using Selenium: http://starcounter.io/guides/web/acceptance-testing-with-selenium/

**Comment by warpech** [comment]
Initial Selenium tests are added. 

Adding them to CI is tracked here https://github.com/Starcounter/CompanyTrack/issues/185
Adding more Selenium tests to this app will be tracked in separate issues.

**Comment by aloscha** [comment]
I wrote it here, because I don't know is it specially or not. I run Selenium test on KitchenSink + luncher and 95% tests fail. Is our test must be also working with luncher? (if yes, then we need to create separate issue to fix them all)?

cc @warpech @miyconst @joozek78

**Comment by warpech** [comment]
Why do the tests fail? I guess it is because the XPath selectors don't match. 

To make the tests run both in Launcher and without it, we need to add discrete IDs to every tested HTML element. 

Maybe we could use some short attributes like `data-testid="kitchensink-123"`. Then it is enough to use a CSS attribute selector `[data-testid=kitchensink-123]` in the test. I would like that.

**Comment by aloscha** [comment]
@warpech I will create new issue with that.

**Comment by aloscha** [comment]
KitchenSink + Luncher fails on Selenium tests #46
