### ISSUE TITLE
Cancel in FileUploder generate error

### ISSUE THREAD

**Issue by aloscha** [StarcounterSamples/KitchenSink#22]
When you add big file (I add file 300mb) and then quickly cancel that one, in Uploading Files we will have:
> FileName	3000,43 MB	-1%	Error uploading file

I think the progress needs to be empty and "Error uploading file" could change to cancel uploading file, because error suggest something wrong with connection (not user action)

**Comment by warpech** [comment]
So basically clicking "Cancel" should reset the state of this component instead of showing a message "Error uploading file".

**Comment by ubbeK** [comment]
[Branch merged to master](https://github.com/StarcounterSamples/KitchenSink/commit/e4903895f989ade52cd50654695afe2e4db3c964)
