### ISSUE TITLE
Change partials used in KitchenSink to use Self.GET

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#23]
Currently, page partials in KitchenSink are attached using `CurrentPage = new ...`, which means that they are not layoutable in Launcher's layout editor.

Change attachent of partials to use `Self.GET`, which will allow to store layout changes.

**Comment by aloscha** [comment]
@miyconst Could you review my commit

**Comment by miyconst** [comment]
I have added some comments to the commits.

**Comment by warpech** [comment]
@aloscha please update the issue once you apply the proposed changes.

**Comment by aloscha** [comment]
@miyconst I do changes what you write about.

**Comment by miyconst** [comment]
@aloscha 

- You should follow our coding style, at least in the internal Starcounter projects. You can read more here: https://github.com/Polyjuice/Polyjuice/wiki/C%23-code-formatting.
- The solution you provided works, but I would prefer to keep the KitchenSink project as clean as possible. Another helper file with 80 lines of code would confuse newcomers, and the project suppose to help to understand Starcounter.

**Comment by warpech** [comment]
I agree with @miyconst. KitchenSink will often be the first point of contact with an app.

I understand that it hurts your eyes to see duplicate `/partial/` handlers. But I'd rather have our apps to look too simple than too sophisticated. 

If they look too simple, it is obvious for an experienced developer how to add abstraction. But if they look too advanced, it is totally non-obvious how to remove abstraction.

**Comment by aloscha** [comment]
@warpech could you review branch #23

**Comment by warpech** [comment]
This looks good to me. @miyconst could you please review? 

I know the code looks redundant, but maybe we can get back to it one day using middleware.

Good news is that now KitchenSink pages are finally layoutable in Launcher's layout editor.

**Comment by aloscha** [comment]
@warpech for me code looks really redundant. But my prev solution (which add one more layer with abstraction) was too complicated

**Comment by miyconst** [comment]
Also looks good to me. 

@aloscha I agree, it's too redundant, and if it was a production app, I would add a helper method to remove the redundancy.

KitchenSink is a sample app composed with small parts. The newcomers won't copy entire KitchenSink, but only one or two examples.

Adding a helper method forces newcomers to learn something which has nothing to do with Starcounter itself, but rather belongs to KitchenSink. Imagine that reading a c# book you would have to read *Helper methods in this book* section before you can understand a code snippet.

Please accept the code redundancy for the simplicity and easy learning.
