### ISSUE TITLE
Add example of using modals

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#25]
Add example of using modals to KitchenSink. 

This example should then be followed by other sample apps (but that's another issue in these apps).

**Comment by miyconst** [comment]
Example added:

![image](https://cloud.githubusercontent.com/assets/6435556/14586717/e3f38402-04a1-11e6-96cc-1f91e708335a.png)

![image](https://cloud.githubusercontent.com/assets/6435556/14586723/f350ea5c-04a1-11e6-9dfb-b9e87ed0af82.png)

`http://localhost:8080/KitchenSink/Dialog`
