### ISSUE TITLE
Add PasswordPage and ChackBoxPage tests

### ISSUE THREAD

**Issue by aloscha** [StarcounterSamples/KitchenSink#29]
Add tests to solution based on selenium.

**Comment by warpech** [comment]
Reviewed.

1. Please prefix every test name with the page name. Otherwise we will have too many `PageLoads` tests.
2. Please change `CheckBoxPageTest` to `CheckboxPageTest`. There is no capital `B` in the checkbox page name.

Thanks!

**Comment by warpech** [comment]
Could you also please give `TextPage_` prefix to text page tests? 

Then it is good to merge.

**Comment by aloscha** [comment]
Yeah, I forgot about that. Fixed

**Comment by warpech** [comment]
Great! Please merge to master
