### ISSUE TITLE
Add tests to TextareaPage

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#31]
Add tests to TextareaPage, based on the existing tests for TextPage as well as the information provided at http://starcounter.io/guides/web/acceptance-testing-with-selenium/

**Comment by ubbeK** [comment]
Tests passed on TeamCity personal run #2.1.1777

@warpech: ready for review/merge

**Comment by warpech** [comment]
Looks very well! But in other tests, for example https://github.com/StarcounterSamples/KitchenSink/blob/master/test/KitchenSink.Tests/Tests/PasswordPageTest.cs#L22-L30, `PageLoads` test checks if the menu click works correctly. Could you please add a similar check for `TextareaPageTest`?

**Comment by ubbeK** [comment]
Forgot to add reference in commit comment to Issue: [TextareaPage_PageLoads updates](https://github.com/StarcounterSamples/KitchenSink/commit/9b582ca209041952369f47cad0ed1c5125c51b4a)

**Comment by warpech** [comment]
Looking good now! Please merge to master, close the issue and remove the branch.

**Comment by ubbeK** [comment]
Merged to master and branch removed
