### ISSUE TITLE
KitchenSink Selenium tests are failing on build servers

### ISSUE THREAD

**Issue by alemoi** [StarcounterSamples/KitchenSink#33]
Here are examples of builds:
https://teamcity.starcounter.org/viewLog.html?buildId=2478&tab=buildResultsDiv&buildTypeId=Starcounter_DevelopNightly

https://teamcity.starcounter.org/viewLog.html?buildId=2507&tab=buildResultsDiv&buildTypeId=Starcounter_PnextDailyWindows

**Comment by warpech** [comment]
Sorry I missed it. Is it still relevant or was it fixed by increasing timeouts?

**Comment by warpech** [comment]
Closing, because there is no sign of this still being an issue. Most of the time the problem boils down to increasing the `MaxDurationSeconds` value in https://github.com/StarcounterSamples/KitchenSink/blob/master/kitchensink_selenium_test_conf.json
