### ISSUE TITLE
Change KitchenSink to use implicit standalone mode

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#37]
Remove `Partial.cs` file from the project. Switch to use middleware, as presented in:  https://github.com/Starcounter/Starcounter/issues/3451#issuecomment-199349823

**Comment by warpech** [comment]
This part in `Program.cs` is redundant (by `JsonAutoSessions`) and should be removed:

```
                if (session == null) {
                    session = new Session(SessionOptions.PatchVersioning);
                }
```

**Comment by aloscha** [comment]
Fixed in rv

**Comment by warpech** [comment]
Thanks. Looking good now. 

This needs to be tested (with and without Launcher) after https://github.com/Starcounter/Starcounter/issues/3539 is fixed.

**Comment by warpech** [comment]
@aloscha, please comment out the line `app.Use(new JsonAutoSessions());` and revert the commit https://github.com/StarcounterSamples/KitchenSink/commit/3989d0d373cea16095de045cc52697861b83acd0, because it doesn't work until https://github.com/Starcounter/Starcounter/issues/3575 is fixed.

After that, make sure that Selenium tests are passing and merge to `master`

**Comment by aloscha** [comment]
Merged into master.
