### ISSUE TITLE
After uploded image receive error 1006

### ISSUE THREAD

**Issue by aloscha** [StarcounterSamples/KitchenSink#38]
After successfully uploaded image in bottom box We see Socket Error Code: 1006
![image](https://cloud.githubusercontent.com/assets/5141943/15040520/d3cf7b4a-12b5-11e6-9b50-50a7bcbeefc4.png)

**Comment by warpech** [comment]
@ubbeK may I assign this to you? It seems related you your recent fix

**Comment by ubbeK** [comment]
@warpech: I´ll take a look at it.

**Comment by alemoi** [comment]
I was asked to check this tonight and its the following: client upon finish of upload sends Close frame with status code 1000, the gateway responses with the same close frame, however what I see on the client is status code 1006, **regardless** of which status code the server sends. This is very strange. I verified with RFC and ws Close response seems correct. Could it be that client behaves wrongly?

**Comment by aloscha** [comment]
It's really strange, It's worked on FF and Edge, but not on Chrome (for me)

**Comment by alemoi** [comment]
I have found the issue, related to how the TCP connection is closed after WebSocket close handshake. I guess in Chrome more strictness was added recently. Going to test and push the test tomorrow.

**Comment by alemoi** [comment]
The fix is pushed to develop/pnext, available in the following nightly. It was a tricky one to find :smiley: Thank you for reporting @aloscha

**Comment by alemoi** [comment]
Please close the issue, once you check that its working for you as well :)

**Comment by aloscha** [comment]
After @alemoi fix in starcounter vesrion 2.2.1.2147 (15 May 2016 16:23:32) everything works like a charm.
