### ISSUE TITLE
When running in Launcher, text inputs are not clickable

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#4]
To reproduce:

1. Start Launcher
2. Start KitchenSink
3. Go to http://localhost:8080/KitchenSink/Text
4. Try to type in the "Name" field

**Comment by tomalec** [comment]
Seems to be related to the general "z-index with Shadow DOM" problem. Still digging, for clean solution.

**Comment by tomalec** [comment]
Quick fix: Update all your layouts, to hide `dom-bind-notifier`
Nice fix: Fix the rendering of items `100% x 0`

**Comment by tomalec** [comment]
Here is old issue on this topic https://github.com/Juicy/juicy-tile-grid/issues/18

**Comment by tomalec** [comment]
I have created issue https://github.com/Juicy/juicy-tile-grid/issues/26 to reflect the root cause of this issue in juicy-tile-grid
