### ISSUE TITLE
Add example of "callback" behavior

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/KitchenSink#43]
Yesterday I was asked by AdFenix guys to provide a code sample of how to show a message once a button was pressed and response came back from server.

The following examples should be implemented:

- Save button is disabled after click. Revert button state back after server response.
- Save button is disabled and loading icon shown once clicked. Revert button state back after server response.
- Show "Data successfully saved" message once server responded.
- Show "Failed to save data" message once server responded.
- Hide the successfully message by timeout.

The behavior should be demonstrated on a plain form and inside table rows.

**Comment by miyconst** [comment]
A new page has been added:

![image](https://cloud.githubusercontent.com/assets/6435556/15214016/dafc7b80-184a-11e6-823c-1786cc34ddee.png)

**Comment by miyconst** [comment]
cc @aloscha, @warpech, @ubbeK

**Comment by aloscha** [comment]
For me looks well.
If I good remeber, @warpech says that we need to create selenium test for new tabs and examples in KitchenSink

**Comment by ubbeK** [comment]
It's a good demonstration.
