### ISSUE TITLE
Selenium test, sometimes crashes

### ISSUE THREAD

**Issue by aloscha** [StarcounterSamples/KitchenSink#44]
Sometimes, when I run all tests, few of them get timeout 14s like `ButtonPageTest_DisabledButton`. But after that I run it alone and test pass.

I think it could be linked with too short timeout. (It happens on edge browser)

**Comment by warpech** [comment]
Does Selenium Server tell you what line of code in `ButtonPageTest_DisabledButton` produces the timeout?

**Comment by aloscha** [comment]
This one `wait.Until(x => !label.Text.Equals(originalText));`

But when I start only that test, everythink looks good and test pass

**Comment by warpech** [comment]
Sure, then just try to increase the timeout. 

But I think there is no reason why timeout should be changed only in **this** particular test. The test should take no longer than the other 50 tests for this app. We need to either increase the timeout in all tests or find the reason why does it fail here.

**Comment by warpech** [comment]
Fixed in PR #83.
