### ISSUE TITLE
MultiSelect return error in console

### ISSUE THREAD

**Issue by aloscha** [StarcounterSamples/KitchenSink#53]
Please run KitchenSink with Launcher (I don't test it without it) and then go to MultiSelect tab and click to some country ex. `Sweden`. In console occurs error:

      juicy-tile-list.html:104 juicy-tile-list can only render DOM element nodes. Provided input contains a text node which cannot be rendered. Wrap it in a <div> to fix the problem. Problematic text node:  ";
                  "  ( /KitchenSink/MultiselectPage.html )filterOutText @ juicy-tile-list.html:104filterNodes @ juicy-tile-list.html:102proto.createItemsList @ juicy-tile-list.html:424(anonymous function) @ juicy-tile-list.html:374
      juicy-tile-list.html:104 juicy-tile-list can only render DOM element nodes. Provided input contains a text node which cannot be rendered. Wrap it in a <div> to fix the problem. Problematic text node:  ";
                  "  ( /KitchenSink/MultiselectPage.html )filterOutText @ juicy-tile-list.html:104filterNodes @ juicy-tile-list.html:102proto.createItemsList @ juicy-tile-list.html:424(anonymous function) @ juicy-tile-list.html:374

**Comment by warpech** [comment]
Related to https://github.com/StarcounterSamples/KitchenSink/issues/46

**Comment by miyconst** [comment]
@aloscha please check whether this issue is still valid, I can't reproduce it.

**Comment by aloscha** [comment]
I get latest version of Launcher and KitchenSink and nothing, I think issue could be closed

**Comment by miyconst** [comment]
Then close it please :).
