### ISSUE TITLE
Change the data source of the GeoPage to be a database class

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#54]
Judging from yesterday's experience on CodeNight, it does not make sense to use something that is NOT a database class as the primary data source for a page in the KitchenSink.

Therefore I think GeoPage needs to be changed. Maybe something else too.

**Comment by warpech** [comment]
@mnosek can you do this? @aloscha can help

**Comment by Mnosek** [comment]
I've created a pull request, please review it.

**Comment by warpech** [comment]
Pull request accepted and merged
