### ISSUE TITLE
Remove old and unused branches

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/KitchenSink#58]
We have some old branches in KitchenSink, which were not updated for almost half a year.

Authors of the branches, please review the state and remove if they are no longer needed.

cc @warpech, @aloscha, @alemoi

**Comment by alemoi** [comment]
Thanks for reminding. Removed my branch `alexey`.

**Comment by miyconst** [comment]
Thanks @alemoi.

**Comment by warpech** [comment]
I have removed the branches that I find redundant.
