### ISSUE TITLE
HTML bug on DropdownPage

### ISSUE THREAD

**Issue by Mnosek** [StarcounterSamples/KitchenSink#61]
Closing tag is broken here:
https://github.com/StarcounterSamples/KitchenSink/blob/0ee14302c9e299aa680487d22aeb6f5eeb13f45f/src/KitchenSink/wwwroot/KitchenSink/DropdownPage.html#L38

**Comment by diliger** [comment]
Something strange is going here.

When I open the branch in VisualStudio I can't see the bug in code:
![image](https://cloud.githubusercontent.com/assets/15857369/19832732/bcfcd45c-9e34-11e6-8b9d-597c6861e255.png)

And directly on Github I can't edit the file with browser:
![image](https://cloud.githubusercontent.com/assets/15857369/19832747/ebce355a-9e34-11e6-8019-009901e65253.png)

Also I can't run KitchenSink with standard launcher and Starcounter-DevelopNightlyBuilds-2.2.1.3184:
![image](https://cloud.githubusercontent.com/assets/15857369/19832754/186d72d8-9e35-11e6-9561-a9b208d6da40.png)


Any ideas?

**Comment by diliger** [comment]
Well, found it in master branch.

Fixed in master branch.
