### ISSUE TITLE
Update testing information in README.md

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#63]
Update testing information - test.bat starts KitchenSink automatically.

**Comment by warpech** [comment]
The above is not true, but still the testing information in `README.md` needs updating.

@KmaTTi89 please update https://github.com/StarcounterSamples/KitchenSink/blob/develop/README.md#run-the-test-from-command-line. 

It seems that point 2 can be removed and points 3, 4, 5 should be changed to use the BAT files.

**Comment by KmaTTi89** [comment]
I will change that

**Comment by KmaTTi89** [comment]
Done in https://github.com/StarcounterSamples/KitchenSink/pull/96

**Comment by warpech** [comment]
Thanks, closing
