### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#72]
Add a new page that shows pagination.

Pagination needs to be performed on the server side with database objects.

On the client side we can use Bootstrap.

Make sure that there are the following controls:
- dropdown to control number of elements per page
- previous page button
- next page button
- button to specific page numbers (but not all of them... if there are 100 pages, we don't want 100 buttons)

Do the work on a separate feature branch started from `develop` (see [Branching](https://github.com/StarcounterPrefabs/Guidelines))

Please also include tests with this new page (see [Acceptance testing with Selenium](http://starcounter.io/guides/web/acceptance-testing-with-selenium/))

**Comment by warpech** [comment]
SQL docs might come handy:

- http://starcounter.io/guides/sql/fetch/
- http://starcounter.io/guides/sql/offsetkey/

**Comment by Mackiovello** [comment]
The new pagination page can be found [here](https://github.com/StarcounterSamples/KitchenSink/tree/pagination).

This page works great in Chrome. 

I'm having two main problems: first, the buttons refuse to work in Edge and Firefox. I've tried to find the error but have so far not been able to localize it. Could you take a look at the code and see what I've done wrong? 

The other issue is that I'm struggling to get Selenium working. The tests that we have give me either this error: 
![capture1](https://cloud.githubusercontent.com/assets/19392292/19850778/a2ea4046-9f5a-11e6-9c66-5d85f533363c.PNG)
or this error:
![capture2](https://cloud.githubusercontent.com/assets/19392292/19850783/a98fcf74-9f5a-11e6-8e29-4a837911cdcd.PNG)

The drivers are together with the standalone server in c:/selenium and I've added the Selenium IDE in Firefox.

**Comment by warpech** [comment]
You are on a good path! Some advice:

1) HTML rule that will save you a lot of trouble: Never use an `<a>` element as a button without href value. When you want to have a button, use `<button>` or just `<span>`.

We can learn from Bootstrap [source code](https://github.com/twbs/bootstrap/blob/v3.3.7/dist/css/bootstrap.css#L4711-L4774) that for Bootstrap it is actually preety OK to replace all `<a>` elements with `<span>`, so please start by doing that.

----

2) Never use `<` and `>` in HTML for anything else than opening/closing tags. If you want to display `<` and `>`, you need to encode it using HTML entities: `&gt;` and `&lt;`.

----

3) Is this `span` really needed here: `<span class="polymerIssue2497fix">&gt;</span>`? Why not just `&gt;`?

----

4) If I recall correctly `value` attribute works fine only on Polymer elements and form elements. 

```html
<!-- This works in all browsers -->
<button value="{{model.NextPage$::click}}" onclick="++this.value">xyz</button>

<!-- This only works in Chrome -->
<span value="{{model.NextPage$::click}}" onclick="++this.value">xyz</span>
```

@tomalec, @miyconst - do you know if this was ever reported to Polymer? I can't find the issue.

Anyway, workaround is to use `on-click` rather than `onclick`:

---

5) This is not correct DOM event handler:

```js
template.onChangePageClick = function () {
                template.set("model.ChangePage$", event.currentTarget.innerHTML);
            };
```

This is correct (notice "event" parameter):

```js
template.onChangePageClick = function (event) {
                template.set("model.ChangePage$", event.currentTarget.innerHTML);
            };
```

----

6) Regarding Selenium errors. The `path to the driver executable` is probably you have not added `C;\selenium` to PATH. If this happens to be the reason, could you please add a note about that to http://starcounter.io/guides/web/acceptance-testing-with-selenium/?

---- 

7) Regarding `Edge tests are disabled` - this is not your system's fault, but deliberate ignore comment created by @miyconst: https://github.com/StarcounterSamples/KitchenSink/blame/fad83975ec3b4ebf6201458ea228547e6756d507/test/KitchenSink.Tests/BaseTest.cs#L32

**Comment by miyconst** [comment]
>do you know if this was ever reported to Polymer? I can't find the issue.

I don't think it was ever reported, and I would not hope to get a fix for it, since there are many much more serious issues they are not going to fix, and just switching to Polymer 2.0.

**Comment by Mackiovello** [comment]
All the code is now corrected. I switched to buttons from using <code>a</code> tags. I noticed a weird thing. With <code>onclick</code> you need to click twice in Firefox for it to react the first time you use the button. In Chrome there's no issue like that. If I instead us <code>onmousedown</code> it works as intended. I don't know if this is a error you've seen before.

I'll add the selinium tests as fast as possible.

Is there anything that needs to be changed in the code-behind? I'm not sure if I've solved it the optimal way.

**Comment by tomalec** [comment]
> do you know if this was ever reported to Polymer? I can't find the issue.

I would say that it should not work as native `<span>` does not have `value` property.

Anyway as @miyconst said, we should rather migrate to 2.x sooner, and check how it behaves there, I would not bet for any support of 1.x template binding.

**Comment by Mackiovello** [comment]
Pagination has been added to KitchenSink
