### ISSUE TITLE
Flaky tests in KitchenSink

### ISSUE THREAD

**Issue by joozek78** [StarcounterSamples/KitchenSink#75]
Flaky test: TextPageTest("firefox").TextPage_TextPropagationOnUnfocus
Go to https://teamcity.starcounter.org/project.html?projectId=Starcounter_Apps_KitchenSink&testNameId=7318267521195939949&tab=testDetails
 and see that this test sometimes fails for no apparent reason. Check if you can find the reason for this (race condition?) and fix if possible. If you can't find the reason after investigation please close this issue with a proper comment

**Comment by joozek78** [comment]
Another flaky test: ValidationPageTest("firefox").ValidationPage_ValidRequireInput

**Comment by warpech** [comment]
Fixed with PR #83, thanks for reporting
