### ISSUE TITLE
Create example with lazy data loading

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/KitchenSink#78]
There should be an example with lazy data loading showing the following:

- Table of some dummy data.
- Tooltip on row hover.
- The data inside the tooltip should be loaded in async way on hover.
- While the data is loading, a loading icon should be shown.

**Comment by Joltrix** [comment]
This Issue should be completed. 

If a user hovers a row(person), the data starts to load. When the data is ready to be "retrieved", after the loading is finished, it only "applies" the data if that person is still being hovered.

This is possible to "abuse", by hovering row A (> starting the loading), and then dehovering (>visually cancel the loading), and then rehovering row A (if the loading hasnt completed yet, it continues where it left off), which gives the impression of instant loading.

I don't know if this is considered a big issue though.


@Mackiovello Could you check to see if everything works properly? And feel free to come with feedback about the typed text. - It's the "feature/lazy-loading" branch in KitchenSink, branched off of the develop branch

**Comment by Mackiovello** [comment]
As I've said before, it looks good. 

Though, it's quite a big issue that the lazy loading is not properly cancelled when the mouse is moved out of the field. This gif highlights that:
![agif](https://cloud.githubusercontent.com/assets/19392292/20457105/572bce3e-ae84-11e6-8ddd-f0d06b484014.gif)

When that is fixed and you've replaced the placeholder text, then I would consider it to be a great addition to KitchenSink.

**Comment by miyconst** [comment]
>Though, it's quite a big issue that the lazy loading is not properly cancelled when the mouse is moved out of the field. 

@Mackiovello please describe more. How it should be, and how it is. For me it just blinks too much.

Please also check the code, whether it is easy to read and learn from it.

**Comment by Joltrix** [comment]
@mackiovello are you sure you are looking at the right branch? Cause what you showed in the gif should be fixed :O also, there shouldn't be any placeholder text. I'll take a look at it tomorrow morning though

**Comment by Mackiovello** [comment]
It looks good to me. 

One thing to improve is to either shorten the comments, put them on separate lines, or both. Right now you often have to scroll horizontally to read them which is kind of annoying.

**Comment by Joltrix** [comment]
Changed the comments a bit, and made a pull request :)

**Comment by miyconst** [comment]
@Mackiovello you should be more careful when reviewing the code ;)

- This [line of code](https://github.com/StarcounterSamples/KitchenSink/blob/feature/lazy-loading/src/KitchenSink/LazyLoadingPage.json.cs#L66) schedules 100 session tasks, while only single task does something. Session task is an expensive operation which locks entire sessions. It should be used only when necessary.
- This [line of code](https://github.com/StarcounterSamples/KitchenSink/blob/feature/lazy-loading/src/KitchenSink/LazyLoadingPage.json.cs#L82) would fail if our list contains a couple of people with the same first name.

**Comment by Joltrix** [comment]
@miyconst Ah, thats true! I'll fix em right away! :)

**Comment by miyconst** [comment]
@Mackiovello it's your turn now ;)

**Comment by miyconst** [comment]
Closing the issue as done.
