### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#85]
We aim to increase test coverage in Kitchen Sink as close to 100% as possible.

@KmaTTi89 is working on this right now. The solution is tracked in #83

Question to @KmaTTi89 can you attempt testing the file upload page as one of your priorities this week?

**Comment by KmaTTi89** [comment]
@warpech Yes, I can.

**Comment by warpech** [comment]
Fixed in PR #83.
