### ISSUE TITLE
Dropdown page - selects are empty on fresh database (have only two default values)

### ISSUE THREAD

**Issue by KmaTTi89** [StarcounterSamples/KitchenSink#86]
### Steps to reproduce
1. Create fresh database for KitchenSink
2. Go to Dropdown page
3. Open second select, it has only two options
4. Open next select, it has only two options
5. Go to Autocomplete page
6. Go back to Dropdown page
7. You can see that second and third select have more options 
### Expected result

Selects on dropdown page should have default options don't depends on Autocomplete page options

##### Starcounter version 
Starcounter 2.3.0.5523
##### Involved apps' version

KitchenSink Dev
 
##### Browsers affected
All

**Comment by warpech** [comment]
Do you need this fixed before merging #83 to `develop`?

**Comment by KmaTTi89** [comment]
If you want green build for KitchenSink develop then yes :)

**Comment by warpech** [comment]
@un-tone can you fix this? This is actually not only about AutocompletePage.

Right now, `BreadcrumbPage.json.cs`, `Dropdown.json.cs`, `AutocompletePage.json.cs` `PaginationPage.json.cs` create sample data only when you visit these pages.

This should be changed to create the sample data on the application start.

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterSamples/KitchenSink/pull/89

**Comment by un-tone** [comment]
Closing as done.
