### ISSUE TITLE
Button page - one of the self enabling/disabling button doesn't work correctly (the one with TAKE ONE REGENERATING CARROT text)

### ISSUE THREAD

**Issue by KmaTTi89** [StarcounterSamples/KitchenSink#87]
### Steps to reproduce
1. Go to Button page
2. Click on Self enabling/disabling button named TAKE ONE REGENERATING CARROT

### Expected result
User should see Currently Regenerating text under the button after clicking
### Actual result
The text is not always displayed (try click on the button several times)

##### Starcounter version 
2.3.0.5523

##### Involved apps' version
KitchenSink Dev

ALL

**Comment by warpech** [comment]
Do you need this fixed before merging #83 to `develop`?

**Comment by KmaTTi89** [comment]
If you want green build for KitchenSink develop then yes :)

**Comment by warpech** [comment]
@un-tone can you pls take this?

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterSamples/KitchenSink/pull/88

**Comment by un-tone** [comment]
Closing as done.
