### ISSUE TITLE
None of the tools works

### ISSUE THREAD

**Issue by tomalec** [StarcounterSamples/KitchenSink#94]
### Steps to reproduce
```sh
cd tools
run.bat
```

### Expected result
App should run.

### Actual result
```log
ScErrExecutableNotFound (SCERR10019): The executable file cound not be found. File: "D:\repos\PolyjuiceProjects\Polyjuice\KitchenSink\tools\bin\Debug\KitchenSink.exe"
Version: 2.3.0.5701.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10019.

Type "star -h" to see help
Type "star 10019" to launch the help page for error 10019
```

##### Involved apps' version
https://github.com/StarcounterSamples/KitchenSink/commit/7b0f93d29d85d9278e846da38c186142269a46a7
 
##### Browsers affected
n/a

**Comment by warpech** [comment]
Thanks for reporting. We will fix that in https://github.com/StarcounterSamples/KitchenSink/pull/83 and https://github.com/StarcounterPrefabs/Guidelines/issues/6

**Comment by warpech** [comment]
Fixed on `develop`.
