### ISSUE TITLE
Investigate "Parallelizable" tests

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#95]
In PR https://github.com/StarcounterSamples/KitchenSink/pull/62, @miyconst proposed to run tests in parallel.

The above PR had to be closed because of the incompatibilities, but the research that @miyconst has started there, should be continued.

@KmaTTi89 can you investigate if the new test project can use Nunit3 `[Parallelizable]`?

**Comment by KmaTTi89** [comment]
@warpech 
Yes, I can

**Comment by KmaTTi89** [comment]
@warpech 
Done in https://github.com/StarcounterSamples/KitchenSink/pull/99

**Comment by warpech** [comment]
Thanks, but please do not close an issue until a PR was approved and merged.
