### ISSUE TITLE
Master and develop branch builds are failing

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/KitchenSink#98]
@KmaTTi89 any idea why `master` and `develop` branch builds are failing? `new_tests_project` branch was building OK.

<img width="906" alt="screen shot 2017-02-23 at 19 13 53" src="https://cloud.githubusercontent.com/assets/566463/23272633/55fe9aa0-f9fc-11e6-943e-174134ef3547.png">

**Comment by KmaTTi89** [comment]
@warpech 
Teamcity is down again for me, I can't investigate this

**Comment by warpech** [comment]
Yeah, TeamCity is now accessible only though the new VPN, which is accessible only from the office. We will need to give you a personal new VPN account to access from home.

**Comment by KmaTTi89** [comment]
So we have VPN that works only for office IP? 
What is the purpose to have vpn that works only from particular network? :)
Nevermind...

**Comment by warpech** [comment]
The purpose of the VPN is to work from any network, but you need an account to dial in. So far only the office has the VPN account to dial in.

**Comment by KmaTTi89** [comment]
Done.
Problem was incorrect powershell version selected in TC to run script, I don't know who changed that.
